export enum NotificationType {
    RENTAL_REQUEST = 'RENTAL_REQUEST',
    RENTAL_REQUEST_CONFIRMATION = 'RENTAL_REQUEST_CONFIRMATION',
    RENTAL_REQUEST_REJECTED = 'RENTAL_REQUEST_REJECTED',
    RETURN_REMINDER = 'RETURN_REMINDER',
    REVIEW_RECEIVED = 'REVIEW_RECEIVED',
    OTHER = 'OTHER'
}