quarkus.application.name=toolloopapi

# ========================
# HTTP / CORS
# ========================
quarkus.http.port=8080
quarkus.http.ssl-port=8443
quarkus.http.insecure-requests=enabled
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type
quarkus.http.cors.exposed-headers=*
quarkus.http.cors.access-control-allow-credentials=true

# ========================
# File uploads
# ========================
quarkus.http.body.uploads-directory=/tmp/
quarkus.http.body.delete-uploaded-files-on-end=false
quarkus.http.limits.max-form-attribute-size=50M

# ========================
# MySQL / Aiven datasource
# ========================
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=avnadmin
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://tool-loop-db-aereodb.g.aivencloud.com:20236/defaultdb?sslMode=REQUIRED

# Connection pool
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10

# ========================
# Hibernate ORM
# ========================
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL8Dialect

# ========================
# Logging
# ========================
quarkus.log.level=INFO
quarkus.live-reload.instrumentation=true
quarkus.naming.enable-jndi=true

# ========================
# AWS S3
# ========================
aws.s3.filesBucketName=toolloop-files
aws.s3.region=us-east-1
aws.s3.toolloop-files.cloudfront-url=
aws.s3.accessKeyId=
aws.s3.secretAccessKey=


# ========================
# OpenAPI / Swagger
# ========================
quarkus.smallrye-openapi.enable=false
quarkus.swagger-ui.always-include=true

# ========================
# JWT
# ========================
jwt.secret.key=1873e62e781f5473658c760ebd3770173186e636b32898a48e09805b30512f08
smallrye.jwt.verify.key.format=BASE64
mp.jwt.verify.issuer=https://toolloop.com
smallrye.jwt.verify.key=${jwt.secret.key}

# ========================
# Native build
# ========================
quarkus.native.container-build=true
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl

# ========================
# WebSocket
# ========================
websocket.heartbeat.interval.seconds=30